language: node_js

branches:
  only:
    - feature/static-dist
    
deploy:
  provider: s3
  access_key_id:
    secure: BGGiHjaaykF4t9ipFESZ88bqfWRX1J7RpUvF/1Kn9iILiqZWSBRyw+wcIif6ZuEweN/O6djX4pNvgzRN8OJlRjdsl+yrtK2xO74+znhFm4dRvCz1ILrqjYr3FahRafIaV44Th4hvLeilxdQBBpDHnTUIsDl3k2NUXv7jdo/rMZ4RG/9M4YxDQLmPoHgG4pT7G8E2xiFFxmVlg1iOJ5GCxZrWXcQ+38mupUtPTSpsziZRLOaspxJxzh2+V7MVsrStLYcuFxRMF8rduRu2GPyzgFrKG/y0HtH8ofcOSxAeF0lFjZrGu0hbKq1JiKq0MedOOtzJLVfrZZg8dpJurAm0q6WSPzl2sjGiz0I7lyWAc2Tc2gbe0oTeYxDHDEWeK7F9ZgWdZC7SgvngsyTF9E6hpNITXLD9xQtPfh1Gm3p4F5Y0FSH7DCSWEIbSvL7qCMWEX3qSsTdZNZvYAywe6+BQ04qrFxIdqo5IVERy8ezhIch37q2mC8QXoKsYtfCv7KRq9ciUv5x5pVCJAgojrZg5T469Dt19l3tOjMMWSDMfhLMExnA3LvrttvO0sqLDHzja/6txjscS3Z1bt4/1bU4ODMYa4K4p6XFoS3vlPIlgi4l9VFtFG9+L67ep6nrj44/novMOq4rpGZtfDqOEHCtFf/KIHztSNudOwjB8a5KPAqI=
  secret_access_key:
    secure: hV5DYGIdsZ3ZREHQ3u0wNYHwj2r/dSM301dcPwe/RC66lQNCRQLItOk4paDzbRzds75k1yrOWreS+ngN19Y4ULltK9HBGC/VX/ZqsvRyOGOUrq5+5xlUQDiXSQjh1oPtbzMNz4moATHAPoxG2+5mWsWSXaj1V0hoawJkkhE9ZHb1WRelfdHQEx9Hqtz1fTXcUf3kSGE4or6S+eAUVuqzPKjKzYKdsiYDpIAMVYA3KTtJ4DxtvcbCAZjEwAkKoax9cs1PgoMurteCtOG8utPzaSf8EYMs22+do1cr8jFD0sMW+JItfcbQKtHmqht0AOBQbSAG14SlHmLlueO4OuFIux1jjKSGAZmaNpS+5N+pprVhGsIk0nCyrxqZTx8Ld1lwHWWqX3ir5XE4h+jB6sCi+e9rfGNG12eRYw96XA4L5re5zutb/YGf2rkyDZEwGhHs3StmpTjlgjxDIVf5yuFdYRjaY1a1aeh/JFvUKLM8OBArhpFIq56h37PD9H80nW2/6b6POYUtCBeB0YO/XdIgOMfkXFW6dRpgJZL6TVnu6Fh43PNaDVYuwJ3gOLSwF542/+mjWtgZlaBv6Bw9rodZk2+DOfDNRdoF15JGhNxvaw8/oQuuHMWl+8A+OG0skM6h1N5kulEa+MmaxwbgzPxlx6DYRFJNgyZlZusuzi31EME=
  bucket: "sprocketleague.lance.gg"
  region: us-west-2
  local_dir: dist
  skip_cleanup: true
  on:
    branch: feature/static-dist